const para = [
    `In the heart of a bustling city, amidst towering skyscrapers and neon lights, a lone figure strolled through the crowded streets. His name was Jack, a man with a mysterious past and a troubled soul. He moved with purpose, his eyes scanning the faces that passed him by, searching for something he couldn't quite name. As he turned a corner, he caught a glimpse of her—a woman with fiery red hair and eyes that sparkled with mischief. With a quickened pace, Jack followed her into the night, unaware of the adventure that awaited him.`,
    `The moon hung low in the sky, casting an ethereal glow over the deserted beach. Sarah stood at the water's edge, the cool breeze tousling her hair as she gazed out at the endless expanse of the ocean. Memories flooded her mind, memories of love lost and dreams left unfulfilled. But tonight, she felt something stirring within her—a sense of hope, of possibility. With a determined smile, Sarah took a step forward, plunging into the waves with a newfound sense of freedom.`,
    `Deep in the heart of the enchanted forest, where the trees whispered secrets to the wind, a young girl named Lily stumbled upon a hidden glade. Surrounded by lush greenery and vibrant flowers, she felt a sense of peace wash over her—a feeling she had long been searching for. As she explored the magical realm, she discovered that she was not alone. Creatures of all shapes and sizes emerged from the shadows, their eyes gleaming with curiosity. And in that moment, Lily knew that she had found her true home`,
    `High above the clouds, in a kingdom of silver and gold, a prince embarked on a quest to save his kingdom from darkness. With his loyal steed by his side, he journeyed across vast deserts and treacherous mountains, facing countless dangers along the way. But as he drew closer to his goal, doubts began to creep into his mind. Would he be strong enough to defeat the evil that threatened to consume his world? With a steely resolve, the prince pressed on, knowing that the fate of his kingdom rested in his hands.`,
    `In the depths of the jungle, where ancient ruins lay hidden beneath a thick canopy of trees, an archaeologist made a startling discovery. Etched into the crumbling stone walls were symbols unlike any he had ever seen before—symbols that held the key to unlocking the mysteries of the past. With trembling hands, he traced the intricate patterns, his heart racing with excitement. But as he delved deeper into the ancient ruins, he unwittingly unleashed a dark force that threatened to consume him and everything he held dear.`,
    `On the rugged cliffs overlooking the stormy sea, a lighthouse keeper tended to his duties with unwavering dedication. Night after night, he stood watch over the churning waters, guiding ships safely to shore with the beacon of light that emanated from his tower. But as a fierce storm descended upon the coastline, the keeper found himself facing his greatest challenge yet. With waves crashing against the rocks below and winds howling through the night, he stood firm, a beacon of hope in the darkness.`,
    `In a quaint village nestled in the rolling hills of the countryside, a young girl named Emily dreamed of adventure beyond the horizon. With her faithful companion—a spirited horse named Blaze—by her side, she galloped across meadows and through dense forests, her laughter echoing through the crisp morning air. But as she ventured farther from home, she encountered dangers she had never imagined, and her courage was put to the test. With each new challenge, Emily grew stronger, her spirit burning bright like the fiery sun that illuminated her path`,
    `Beneath the twinkling stars of a moonlit night, two lovers stole away into the forest, their hearts aflame with passion. Hand in hand, they wandered through the enchanted grove, their laughter mingling with the rustle of leaves overhead. But as they embraced beneath the ancient trees, a shadow fell across the clearing—a shadow from the past that threatened to tear them apart. With tears in their eyes, they vowed to fight for their love, to defy the forces that sought to keep them apart.`,
    `In the heart of a bustling metropolis, where skyscrapers towered overhead and traffic roared through the streets, a young artist found inspiration in the chaos that surrounded her. With a canvas and paintbrush in hand, she captured the energy of the city—the vibrant colors, the frenetic movement, the hidden beauty that lurked beneath the surface. But as she poured her heart and soul into her art, she discovered that the greatest masterpiece of all was the love that blossomed between her and a fellow dreamer, their souls intertwined like brushstrokes on a canvas.`,
    `As the sun dipped below the horizon, casting a golden glow over the tranquil countryside, a weary traveler sought refuge in a humble inn on the outskirts of town. With a heavy heart and a burdened mind, he sought solace in the warmth of the fire and the company of strangers. But as he listened to their tales of adventure and triumph, he felt a glimmer of hope ignite within him—a hope that perhaps, despite the trials and tribulations of life, there was still magic to be found in the world.`
]
export default para;